version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: ecorideclient-zookeeper
    ports:
      - "2181:2181"
    networks:
      - ecorideclient_ecoride-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: ecorideclient-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_MESSAGE_MAX_BYTES: 1504857600
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - ecorideclient_ecoride-network

  eco-ride:
    image: ecoride
    container_name: eco-ride
    environment:
      BOOTSTRAP_SERVERS: kafka:9093
      GROUP_ID: rental
      TOPIC_RESERVATION_RESPONSE: reservation_response
      TOPIC_RESERVATION_REQUEST: reservation_request
      TOPIC_LOCATION_UPDATE: location_update
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - ecorideclient_ecoride-network

  eco-ride-client:
    image: ecorideclient
    container_name: eco-ride-client
    environment:
      BOOTSTRAP_SERVERS: kafka:9093
      GROUP_ID: rental
      TOPIC_RESERVATION_RESPONSE: reservation_response
      TOPIC_RESERVATION_REQUEST: reservation_request
      TOPIC_LOCATION_UPDATE: location_update
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - ecorideclient_ecoride-network

networks:
  ecorideclient_ecoride-network:
    driver: bridge
